Import("env")

env.Append(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("gui_application.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="gui_application")
libenv.ApplyLibFlags()

sources = [
    "gui_application.c",
]

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
